uploads = []

[[generated]]
id = "IOclVNOhJm1DCfxhasho7"
uri = "file://artifacts/namaz-tv/assets/images/icon.png"
type = "image"
title = "namaz prayer times app icon"

[[outputs]]
id = "cpTFDLFjUxv6x_Q7Sc-wj"
uri = "file://artifacts/namaz-tv/namaz-prayer-times-web-build.tar.gz"
type = "unspecified"
title = "Namaz Prayer Times — Web Build"
